# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Users\zhengjie4\source\devtools\3.9\bin\cmake.exe

# The command to remove a file.
RM = C:\Users\zhengjie4\source\devtools\3.9\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\zhengjie4\Nutstore\work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\zhengjie4\Nutstore\work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\Users\zhengjie4\source\devtools\3.9\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\Users\zhengjie4\source\devtools\3.9\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\zhengjie4\Nutstore\work\CMakeFiles C:\Users\zhengjie4\Nutstore\work\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\zhengjie4\Nutstore\work\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sftp_server

# Build rule for target.
sftp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) sftp_server
.PHONY : sftp_server

# fast build rule for target.
sftp_server\fast:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\build
.PHONY : sftp_server\fast

SftpServer.obj: SftpServer.cpp.obj

.PHONY : SftpServer.obj

# target to build an object file
SftpServer.cpp.obj:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\SftpServer.cpp.obj
.PHONY : SftpServer.cpp.obj

SftpServer.i: SftpServer.cpp.i

.PHONY : SftpServer.i

# target to preprocess a source file
SftpServer.cpp.i:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\SftpServer.cpp.i
.PHONY : SftpServer.cpp.i

SftpServer.s: SftpServer.cpp.s

.PHONY : SftpServer.s

# target to generate assembly for a file
SftpServer.cpp.s:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\SftpServer.cpp.s
.PHONY : SftpServer.cpp.s

test_sftp.obj: test_sftp.cpp.obj

.PHONY : test_sftp.obj

# target to build an object file
test_sftp.cpp.obj:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\test_sftp.cpp.obj
.PHONY : test_sftp.cpp.obj

test_sftp.i: test_sftp.cpp.i

.PHONY : test_sftp.i

# target to preprocess a source file
test_sftp.cpp.i:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\test_sftp.cpp.i
.PHONY : test_sftp.cpp.i

test_sftp.s: test_sftp.cpp.s

.PHONY : test_sftp.s

# target to generate assembly for a file
test_sftp.cpp.s:
	$(MAKE) -f CMakeFiles\sftp_server.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sftp_server.dir\test_sftp.cpp.s
.PHONY : test_sftp.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... rebuild_cache
	@echo ... sftp_server
	@echo ... edit_cache
	@echo ... SftpServer.obj
	@echo ... SftpServer.i
	@echo ... SftpServer.s
	@echo ... test_sftp.obj
	@echo ... test_sftp.i
	@echo ... test_sftp.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

